---

- name: Include the install playbook
  ansible.builtin.import_playbook: domenickd3.my_ubuntu_collection.install

- name: Include the configure playbook
  ansible.builtin.import_playbook: domenickd3.my_ubuntu_collection.configure
