---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:22.04
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        configure_user: "molecule-user"
    config_options:
    defaults:
      verbosity: 3
scenario:
  name: default
verifier:
  name: ansible
