---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute pytest testinfra tests
      command: python -m pytest molecule/default/tests/ubuntu-testinfra.py
      register: test_results
      delegate_to: localhost

    - debug: var=test_results.stdout_lines

    ## The following would work (belongs in prepare.yml maybe), but it requires installing pytest on remote host
    # - name: Install pip
    #   ansible.builtin.apt:
    #     name: python3-pip
    #
    # - name: Install virtualenv
    #   ansible.builtin.pip:
    #     name: virtualenv
    #
    # - name: Install pytest
    #   ansible.builtin.pip:
    #     name: pytest
    #     virtualenv: /tmp/testinfra-venv
    #     virtualenv_site_packages: true
    #
    # - name: copy ubuntu-testinfra.py to host
    #   ...
    #
    # - name: Run tests from venv
    #   command: /bin/sh . /tmp/testinfra-venv/bin/activate && pytest ubuntu-testinfra.py
