---
- name: Apt-setup tasks
  when: not ansible_check_mode
  block:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        autoclean: true
        update_cache: true
        upgrade: "yes"
      async: 600
      poll: 0
      register: update_and_upgrade_async
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Wait until apt-get update/upgrade is complete (delay=5)
      ansible.builtin.async_status:
        jid: "{{ update_and_upgrade_async.ansible_job_id }}"
      register: update_and_upgrade_async_result
      until: update_and_upgrade_async_result.finished
      retries: 120
      delay: 5

    - name: Output the result of update and upgade
      ansible.builtin.debug:
        var: update_and_upgrade_async_result
